#!/usr/bin/env zsh

#!/usr/bin/env zsh

command=$1
shift

for arg in "$@"
do
	case $arg in
		--*|-*)
			shift
			;;
		*)
			shift
		;;
	esac
done

case $command in
	save|s)
		changes=$(git status --short)
		( \
			cd $DOTFILES && \
			git add -A && \
			git commit -m "Automatic commit" -m $changes && \
		)
		;;
	*)
		echo "Command not found: $command"
		;;
esac


