#!/usr/bin/env zsh
command=$1
shift

packages=()
purge=true

for arg in "$@"
do
	case $arg in
		--nopurge)
			purge=false
			shift
			;;
		--*|-*)
			shift
			;;
		*)
			packages+=$arg
			shift
		;;
	esac
done

case $command in
	install|i)
		sudo pacman -Syu --needed "${packages[@]}"
		;;
	upgrade|u)
		sudo pacman -Syu
		;;
	remove|r)
		if $purge
		then
			sudo pacman -Rns "${packages[@]}"
		else
			sudo pacman -Rs "${packages[@]}"
		fi
		;;
	search|s)
		sudo pacman -Ss "${packages[@]}"
		;;
	autoremove)
		sudo pacman -Qdtq | sudo pacman -Rs -
		;;
	asexplicit|e)
		sudo pacman -D --asexplicit "${packages[@]}"
		;;
	asdeps|d)
		sudo pacman -D --asdeps "${packages[@]}"
		;;
	# List explicitly installed packages
	list-installed)
		sudo pacman -Qe
		;;
	# List explicitly installed AUR packages
	list-aur)
		sudo pacman -Qqe
		;;
	*)
		echo "Usage: pac command [args]"
		;;
esac
