#!/usr/bin/env zsh

# Shortcuts for package management including upgrading Cargo packages

command=$1
shift

packages=()
purge=true

bold=$(tput bold)
normal=$(tput sgr0)
reset='\033[0m'
blue='\033[0;34m'

for arg in "$@"
do
	case $arg in
		--nopurge)
			purge=false
			shift
			;;
		--*|-*)
			shift
			;;
		*)
			packages+=$arg
			shift
		;;
	esac
done

case $command in
	install|i)
		sudo pacman -Syu --needed "${packages[@]}"
		;;
	upgrade|u)
		echo "${bold}${blue} Upgrading system${normal}${reset}"
		sudo pacman -Syu

		echo "${bold}${blue} Upgrading AUR packages${normal}${reset}"
		yay -Syua

		# Update flatpak
		if [ -x "$(command -v flatpak)" ]; then
			echo "\n${bold}${blue} Updating Flatpak apps${normal}${reset}"
			flatpak update
		fi

		# Update cargo crates via install-update
		if [ -x "$(command -v cargo)" ]; then
			echo "\n${bold}${blue}󰜦 Updating Cargo crates${normal}${reset}"
			cargo install-update -a
		fi

		echo "\n\nUpdates complete! 🎉"
		;;
	remove|r)
		if $purge
		then
			sudo pacman -Rns "${packages[@]}"
		else
			sudo pacman -Rs "${packages[@]}"
		fi

		# Clean up cache for uninstalled packages
		sudo paccache -ruk0
		;;
	search|s)
		sudo pacman -Ss "${packages[@]}"
		;;
	autoremove|ar)
		sudo pacman -Qdtq | sudo pacman -Rs -
		;;
	asexplicit|e)
		sudo pacman -D --asexplicit "${packages[@]}"
		;;
	asdeps|d)
		sudo pacman -D --asdeps "${packages[@]}"
		;;
	info|q)
		sudo pacman -Qi "${packages[@]}"
		;;
	# List explicitly installed packages
	list-installed|ls)
		sudo pacman -Qe
		;;
	*)
		echo "Usage: pac command [args]"
		;;
esac
