#!/usr/bin/env bash
PERPLEXITY_MODEL="sonar-pro"
PERPLEXITY_API_KEY="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"

if [ "$#" -eq 0 ]; then
    echo "Usage: $(basename $0) promt_to_send_to_perplexity"
    echo ""
    echo "  Requirements: jq must be installed, and PERPLEXITY_API defined"
    exit 1
fi

function p() {
    local json_request
    json_request=$(jq -n \
		--arg content "$*" \
		'{
      "model": "sonar",
      "messages": [
        { "role": "system",  "content": "Be precise and concise." },
        { "role": "user",  "content": $content }
      ],
      "stream": false
    }')
    # echo $json_request # uncomment to debug
    
    local json_response
    json_response=$(curl --silent \
		--request POST \
		--url https://api.perplexity.ai/chat/completions \
		--header 'accept: application/json' \
		--header "authorization: Bearer $PERPLEXITY_API_KEY" \
		--header 'content-type: application/json' \
		--data "$json_request")
    # echo $json_response  # uncomment to debug

    echo "$json_response" | jq --raw-output .choices[0].message.content | glow
}

p "$*"
