#!/usr/bin/env zsh
# ==================================================

export DOTFILES="$HOME/.dotfiles"

# ==================================================
# XDG
# ==================================================

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

# ==================================================
# Editor
# ==================================================

export EDITOR="nano"
export VISUAL="code"

# ==================================================
# Software
# ==================================================

export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"

# ==================================================
# zsh
# ==================================================

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# ==================================================
# fzf
# ==================================================

export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# ==================================================
# X11
# ==================================================

export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"

# ==================================================
# NPM
# ==================================================

export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

# ==================================================
# Git
# ==================================================

export GIT_REVIEW_BASE=main

# ==================================================
# PATH
# ==================================================

export PATH="$XDG_CONFIG_HOME/composer/vendor/bin:$PATH"
export PATH="$XDG_CONFIG_HOME/go/bin:$PATH"
export PATH="$NPM_BIN:$PATH"